package com.publiedicto.enumerados;

public enum TipoDeEdicto {

	JUDICIAL("JUDICIAL"), AUDIENCIA_PUBLICA("AUDIENCIA_PUBLICA"), AVISO_LEY_11867("AVISO_LEY_11867"), AVISO_LEY_19550("AVISO_LEY_19550"), BALANCES("BALANCES"), CONCURSO_PUBLICO("CONCURSO_PUBLICO"),
	CONCURSO_DE_ANTECEDENTES("CONCURSO_DE_ANTECEDENTES"), CONCURSOS_Y_QUIEBRAS("CONCURSOS_Y_QUIEBRAS"), CONTRATOS_SOCIALES("CONTRATOS_SOCIALES"), CONVOCATORIAS("CONVOCATORIAS"), FE_DE_ERRATAS("FE_DE_ERRATAS"),
	IRRIGACION_Y_MINAS("IRRIGACION_Y_MINAS"), LICITACIONES("LICITACIONES"), MENSURAS("MENSURAS"), NOTIFICACIONES("NOTIFICACIONES"), REGULARIZACIONES_DOMINALES("REGULARIZACIONES_DOMINALES"), REMATES("REMATES"), SUCESORIOS("SUCESORIOS"),
	TITULOS_SUPLETORIOS("TITULOS_SUPLETORIOS");

	private final String tipo;

	private TipoDeEdicto(String tipo) {
		this.tipo = tipo;
	}
	
	public String getTipoDeEdicto() {
        return tipo;
    }

}
